# docker-compose.example.yml
# This is a sample file. Copy to docker-compose.yml and fill in your actual values.
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile # Your real Dockerfile name
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
      - SECRET_KEY=a_very_long_and_super_secret_key_here
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile # Your real Dockerfile name
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api/v1

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"

volumes:
  postgres_data: