"""Add file_path column to issues table

Revision ID: 931c75af2fcd
Revises: 7270625d4844
Create Date: 2025-07-05 00:06:29.085774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '931c75af2fcd'
down_revision: Union[str, Sequence[str], None] = '7270625d4844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'file_path')
    # ### end Alembic commands ###
